# Generated by Django 5.1.7 on 2025-03-21 12:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Title should be Atleast 5 letters long!'), django.core.validators.MaxLengthValidator(100, 'Title is too long max letters 100')])),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('E', 'EASY'), ('M', 'MEDIUM'), ('H', 'HARD')], max_length=1)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('hints', models.TextField(blank=True, null=True)),
                ('testcase', models.TextField()),
                ('starter_codes', models.JSONField(default=dict)),
                ('solution_codes', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Problems', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='problem_tags', to='problems.tags')),
            ],
        ),
    ]
