# Generated by Django 5.1.7 on 2025-05-01 05:56

import problems.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problems_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='level',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1),
        ),
        migrations.AlterField(
            model_name='problems',
            name='solution_codes',
            field=models.JSONField(default=problems.constants.defaultcodes),
        ),
        migrations.AlterField(
            model_name='problems',
            name='starter_codes',
            field=models.JSONField(default=problems.constants.defaultcodes),
        ),
    ]
