# Generated by Django 5.1.7 on 2025-05-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problems_level_alter_problems_solution_codes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='testcase',
            new_name='testcases',
        ),
    ]
