# Generated by Django 5.1.7 on 2025-05-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_rename_testcase_problems_testcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='testcases',
            field=models.TextField(),
        ),
    ]
