# Generated by Django 5.1.7 on 2025-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problems_testcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='ready_to_solve',
            field=models.BooleanField(default=False),
        ),
    ]
