# Generated by Django 5.1.7 on 2025-05-07 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0005_alter_problems_testcases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_code', models.TextField()),
                ('submission_lang', models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('cpp', 'Cpp'), ('javascript', 'Javascript')])),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('attempted', 'Rejected')])),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
