# Generated by Django 5.1.7 on 2025-05-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
