# Generated by Django 5.1.7 on 2025-05-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submissions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='errors',
            field=models.JSONField(default=dict),
        ),
    ]
