# Generated by Django 5.1.7 on 2025-05-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submissions_errors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='errors',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='description',
        ),
    ]
