# Generated by Django 5.1.7 on 2025-04-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='providers',
            field=models.CharField(choices=[('G', 'GOOGLE'), ('GH', 'GITHUB'), ('P', 'DSA PLATFORM')], default='P', max_length=2),
        ),
    ]
