# Generated by Django 5.1.7 on 2025-05-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.CharField(blank=True, null=True),
        ),
    ]
